version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  TESTING: test
before_build:
- cmd: dotnet restore GradeBook.sln
- ps: echo $env:TESTING
build:
  verbosity: minimal
notifications:
- provider: Webhook
  #url: http://requestbin.net/r/1q07eaw1
  url: https://dev.azure.com/totaltestltd/_apis/public/distributedtask/webhooks/AppVeyor
    #secure: 4laXGhhTJ2svLa2/cJRTVKIC4s8kELIOndoJDMUuD0IpVXCmPcpXJgoS8ba/I14Rz/NtqYtMysUhsl06N2I+Pnrsv4AQDDTae6GJy07UZFrt6kCRcVtQc/9dKWRG0NQbyoZMZ1yWWC2ehtgXJexdcg==
  method: POST
  body: >-
    {
        "buildVersion":  "{{buildVersion}}",
        "status": "{{status}}",
    }
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false