version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore GradeBook.sln
environment:
  testing: test
build:
  verbosity: minimal
notifications:
- provider: Webhook
  url: http://requestbin.net/r/19mrcod1
  method: POST
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false